import{S as l,i as d}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();function u(o){return fetch(`https://pixabay.com/api/?key=45282736-76f00277f987f73abb95d9f87&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()}).catch(s=>{console.log(s)})}function f(o){const t=new l(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),i=document.querySelector(".gallery"),s=o.hits.map(e=>`<div class="image-wrapper">
    <a href="${e.largeImageURL}">
    <img class="gallery-images" src="${e.webformatURL}" alt="${e.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-info">${e.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-info">${e.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-info">${e.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-info">${e.downloads}</p></div>
    </div>
    </div>`).join("");i.insertAdjacentHTML("beforeend",s),t.refresh()}function h(o){const t=document.querySelector(".gallery");t.innerHTML=""}const c=document.querySelector(".search-form"),n=document.querySelector(".loader"),m=document.querySelector(".input-text");c.addEventListener("submit",p);function p(o){o.preventDefault(),h(),n.classList.remove("hidden");const t=m.value.trim().toLowerCase();u(`${t}`).then(i=>{if(i.total===0||t===""){d.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n.classList.add("hidden");return}else f(i);n.classList.add("hidden")}),c.reset()}
//# sourceMappingURL=commonHelpers.js.map
