import{S as d,i as n}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function u(a){return fetch(`https://pixabay.com/api/?key=45282736-76f00277f987f73abb95d9f87&q=${a}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()}).catch(o=>{console.log(o)})}function f(a){const t=new d(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),s=document.querySelector(".gallery"),o=a.hits.map(e=>`<div class="image-wrapper">
    <a href="${e.largeImageURL}">
    <img class="gallery-images" src="${e.webformatURL}" alt="${e.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-info">${e.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-info">${e.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-info">${e.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-info">${e.downloads}</p></div>
    </div>
    </div>`).join("");s.insertAdjacentHTML("beforeend",o),t.refresh()}function h(a){const t=document.querySelector(".gallery");t.innerHTML=""}const l=document.querySelector(".search-form"),c=document.querySelector(".loader"),p=document.querySelector(".input-text");l.addEventListener("submit",m);function m(a){a.preventDefault();const t=p.value.trim().toLowerCase();if(t===""){n.error({position:"topRight",message:"Search query cannot be empty. Please enter a keyword!"});return}h(),c.classList.remove("hidden"),u(t).then(s=>{s.total===0?n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):f(s)}).catch(s=>{n.error({position:"topRight",message:"An error occurred while fetching data. Please try again later."}),console.error(s)}).finally(()=>{c.classList.add("hidden")}),l.reset()}
//# sourceMappingURL=commonHelpers.js.map
